twitter/urls.py
from django.contrib import admin
from django.urls import path
from twitter import views

app_name = "twitter"

urlpatterns = [
    path('', views.MainWebpageView.as_view(), name="index"),
]

twitter/models.py
from django.db import models

from django.contrib.auth.models import User



TWITTER_MAXIMUM_TWEET_LENGTH = 280

TWITTER_MAXIMUM_COMMENT_LENGTH = 60

TWITTER_MAXIMUM_MSG_LENGTH = 64





class Tweet(models.Model):

    content = models.CharField(max_length=TWITTER_MAXIMUM_TWEET_LENGTH)

    creation_date = models.DateTimeField(auto_now_add=True)

    author = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):

        return '[{}] TWEET by {}: {}'.format(

            self.creation_date,

            self.author, self.content[:20])

twitter/views.py
from django.shortcuts import render
from django import views
# Create your views here.

class MainWebpageView(views.View):
    def get (self,request):
        ctx={}
        return render(request,"twitter/index.html",ctx)

twitter/templates/twitter/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'twitter/main.css' %}">
    <title>Django Twitter clone</title>
</head>

<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'twitter:index' %}">Twitter clone</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'twitter:index' %}">Home</a>
            </div>
          </div>
        </div>
      </nav>
    </header>

    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

twitter/templates/twitter/index.html
{% extends "twitter/base.html" %}
{% block content %}
    <h1>WItaj świecie</h1>
{% endblock %}